name: Generate Snake

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: khalilhaider
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: push snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          path: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
